/**
 * @typedef {object} AliasProps
 * @property {React.CSSProperties['marginLeft'] & React.CSSProperties['marginRight']} mx
 * @property {React.CSSProperties['marginTop'] & React.CSSProperties['marginBottom']} my
 * @property {React.CSSProperties['paddingLeft'] & React.CSSProperties['paddingRight']} px
 * @property {React.CSSProperties['paddingTop'] & React.CSSProperties['paddingBottom']} py
 *
 * @typedef {Pick<React.CSSProperties,
 * | 'border'
 * | 'borderBottom'
 * | 'borderColor'
 * | 'borderLeft'
 * | 'borderRadius'
 * | 'borderRight'
 * | 'borderTop'
 * | 'boxShadow'
 * | 'display'
 * | 'overflow'
 * | 'textOverflow'
 * | 'visibility'
 * | 'whiteSpace'
 * | 'alignContent'
 * | 'alignItems'
 * | 'alignSelf'
 * | 'flex'
 * | 'flexBasis'
 * | 'flexDirection'
 * | 'flexGrow'
 * | 'flexShrink'
 * | 'flexWrap'
 * | 'justifyContent'
 * | 'justifyItems'
 * | 'justifySelf'
 * | 'order'
 * | 'gap'
 * | 'columnGap'
 * | 'rowGap'
 * | 'gridColumn'
 * | 'gridRow'
 * | 'gridAutoFlow'
 * | 'gridAutoColumns'
 * | 'gridAutoRows'
 * | 'gridTemplateColumns'
 * | 'gridTemplateRows'
 * | 'gridTemplateAreas'
 * | 'gridArea'
 * | 'backgroundColor'
 * | 'color'
 * | 'bottom'
 * | 'left'
 * | 'position'
 * | 'right'
 * | 'top'
 * | 'zIndex'
 * | 'height'
 * | 'maxHeight'
 * | 'maxWidth'
 * | 'minHeight'
 * | 'minWidth'
 * | 'width'
 * | 'boxSizing'
 * | 'margin'
 * | 'marginBottom'
 * | 'marginLeft'
 * | 'marginRight'
 * | 'marginTop'
 * | 'marginInline'
 * | 'marginInlineStart'
 * | 'marginInlineEnd'
 * | 'marginBlock'
 * | 'marginBlockStart'
 * | 'marginBlockEnd'
 * | 'padding'
 * | 'paddingBottom'
 * | 'paddingLeft'
 * | 'paddingRight'
 * | 'paddingTop'
 * | 'paddingInline'
 * | 'paddingInlineStart'
 * | 'paddingInlineEnd'
 * | 'paddingBlock'
 * | 'paddingBlockStart'
 * | 'paddingBlockEnd'
 * | 'fontFamily'
 * | 'fontSize'
 * | 'fontStyle'
 * | 'fontWeight'
 * | 'letterSpacing'
 * | 'lineHeight'
 * | 'textTransform'
 * | 'textAlign'
 * > & AliasProps} SystemProps
 */
