import styled from 'styled-components';

/**
 * @type {import('styled-components').StyledComponent<'div', import('styled-components').DefaultTheme, SystemProps>}
 * @description The Box component serves as a wrapper component for most of the CSS utility needs.
 * @see [React Box component - MUI](https://mui.com/components/box/)
 */
const Box = styled.div.withConfig({
  shouldForwardProp: (prop, defaultValidatorFn) =>
    prop !== 'color' &&
    prop !== 'display' &&
    prop !== 'height' &&
    prop !== 'width' &&
    defaultValidatorFn(prop),
})(
  ({
    alignContent,
    alignItems,
    alignSelf,
    backgroundColor,
    border,
    borderBottom,
    borderColor,
    borderLeft,
    borderRadius,
    borderRight,
    borderTop,
    bottom,
    boxShadow,
    boxSizing,
    color,
    columnGap,
    display = 'flex',
    flex,
    flexBasis,
    flexDirection,
    flexGrow,
    flexShrink,
    flexWrap,
    fontFamily,
    fontSize,
    fontStyle,
    fontWeight,
    gap,
    gridArea,
    gridAutoColumns,
    gridAutoFlow,
    gridAutoRows,
    gridColumn,
    gridRow,
    gridTemplateAreas,
    gridTemplateColumns,
    gridTemplateRows,
    height,
    justifyContent,
    justifyItems,
    justifySelf,
    left,
    letterSpacing,
    lineHeight,
    margin,
    marginBlock,
    marginBlockEnd,
    marginBlockStart,
    marginBottom,
    marginInline,
    marginInlineEnd,
    marginInlineStart,
    marginLeft,
    marginRight,
    marginTop,
    maxHeight,
    maxWidth,
    minHeight,
    minWidth,
    mx,
    my,
    order,
    overflow,
    padding,
    paddingBlock,
    paddingBlockEnd,
    paddingBlockStart,
    paddingBottom,
    paddingInline,
    paddingInlineEnd,
    paddingInlineStart,
    paddingLeft,
    paddingRight,
    paddingTop,
    position,
    px,
    py,
    right,
    rowGap,
    textAlign,
    textOverflow,
    textTransform,
    top,
    visibility,
    whiteSpace,
    width,
    zIndex,
  }) => ({
    alignContent,
    alignItems,
    alignSelf,
    backgroundColor,
    border,
    borderBottom,
    borderColor,
    borderLeft,
    borderRadius,
    borderRight,
    borderTop,
    bottom,
    boxShadow,
    boxSizing,
    color,
    columnGap,
    display,
    flex,
    flexBasis,
    flexDirection,
    flexGrow,
    flexShrink,
    flexWrap,
    fontFamily,
    fontSize,
    fontStyle,
    fontWeight,
    gap,
    gridArea,
    gridAutoColumns,
    gridAutoFlow,
    gridAutoRows,
    gridColumn,
    gridRow,
    gridTemplateAreas,
    gridTemplateColumns,
    gridTemplateRows,
    height,
    justifyContent,
    justifyItems,
    justifySelf,
    left,
    letterSpacing,
    lineHeight,
    margin,
    marginBlock,
    marginBlockEnd,
    marginBlockStart,
    marginBottom: my ?? marginBottom,
    marginInline,
    marginInlineEnd,
    marginInlineStart,
    marginLeft: mx ?? marginLeft,
    marginRight: mx ?? marginRight,
    marginTop: my ?? marginTop,
    maxHeight,
    maxWidth,
    minHeight,
    minWidth,
    order,
    overflow,
    padding,
    paddingBlock,
    paddingBlockEnd,
    paddingBlockStart,
    paddingBottom: py ?? paddingBottom,
    paddingInline,
    paddingInlineEnd,
    paddingInlineStart,
    paddingLeft: px ?? paddingLeft,
    paddingRight: px ?? paddingRight,
    paddingTop: py ?? paddingTop,
    position,
    right,
    rowGap,
    textAlign,
    textOverflow,
    textTransform,
    top,
    visibility,
    whiteSpace,
    width,
    zIndex,
  })
);

export default Box;
